version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker-config/app/Dockerfile
        ports:
            - 4000:4000
        environment:
            SERVER_PORT: 4000
        volumes:
            - ./app:/src/